version: '3.7'

networks:
  buildernet:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      dev_network:
        ipv4_address: 10.20.0.2
    environment:
      RABBITMQ_DEFAULT_USER: test
      RABBITMQ_DEFAULT_PASS: test
  
  registry:
    image: registry:2
    container_name: registry
    hostname: registry
    ports:
      - "5000:5000"
    networks:
      dev_network:
        ipv4_address: 10.20.0.3
    environment:
      REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /var/lib/registry
    volumes:
      - ./data/registry:/var/lib/registry



