version: '3.7'

networks:
  buildernet:
    ipam:
      driver: default
      config:
        - subnet: 10.2.0.0/24

services:

  # builder:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   container_name: b_builder
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock
  #   environment:
  #     - DOCKER_HOST=unix:///var/run/docker.sock
  #     - DOCKER_DRIVER=overlay2
  #   ports:
  #     - 8001:8001
  #   networks:
  #     buildernet:
  #       ipv4_address: 10.2.0.1

  registry:
    image: registry:2
    container_name: b_registry
    volumes:
      - ./data/registry:/var/lib/registry
    environment:
      - REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY=/var/lib/registry
      - REGISTRY_HTTP_ADDR=0.0.0.0:5000
    ports:
      - 5000:5000
    networks:
      buildernet:
        ipv4_address: 10.2.0.2


